server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hpedu?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: houpe2016
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
        encoding:
          charset: utf-8
          force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  resources:
    static-locations: file:C://static/
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml